#!/bin/bash
# Kellaaeg

echo -n "Sisesta aja väärtus: "
read aeg
if [ $aeg -ge 6 -a $aeg -lt 12 ]
then
	echo "Tere hommikust!" # Kui aja väärtus on 6-12 vahel ütleb Tere hommikust!
elif [ $aeg -ge 12 -a $aeg -lt 18 ]
then
	echo "Tere päevast!" # Kui aja väärtus on 12-18 vahel ütleb Tere päevast!
elif [ $aeg -ge 18 -a $aeg -lt 22 ]
then
	echo "Tere õhtust!" # Kui aja väärtus on 18-22 vahel ütleb Tere õhtust!
elif [ $aeg -ge 22 -a $aeg -le 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]
then
	echo "Head ööd!" # Kui aja väärtus on 22-24  ja 0-6 vahel ütleb Head ööd!
else
	echo "Vale sisend" # Kui mingi muu arv mis ei jää vahemikku siis ütleb vale sisend.
fi
