#!/bin/bash
# kasutaja loomine
grupid="opilased, opetajad"
while :
do
echo -n "Sisesta oma kasutajanimi: "
read kasutaja
egrep "^$kasutaja" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	echo -e "Selline kasutajanimi on juba olemas!"
	exit
else

echo -n "Vali nendest gruppidest üks ($grupid): "
read grupp
if grep -q $grupp /etc/group
then
	useradd -g $grupp -d /home/$kasutaja -s /bin/bash -m $kasutaja
	echo "$kasutaja:$kasutaja" | chpasswd
	echo -e "Kasutaja $kasutaja loodud"
	echo -e "Parool on: $kasutaja"
	echo -e "Teie grupiks on: $grupp"
	echo -e "Teie kodukataloog on: /home/$kasutaja"
else
	echo -e "Sellist gruppi ei ole olemas!"
fi
fi
echo ""
echo -e "Vajuta CTRL+C, et lõpetada!"
done
