#!/bin/bash
# Ülesanne 4 täiendus
for (( arv=1; arv<21; arv++ ))
do

if [ $arv -eq 0 -o $arv -eq 1 ]; then
	echo "$arv - ei ole algarv"
else
	jagaja=2
	jaak=$(expr $arv % $jagaja)
	while [ $jaak -ne 0 ]
	do
		jagaja=$(expr $jagaja + 1)
		jaak=$(expr $arv % $jagaja)
	done
	if [ $arv -eq $jagaja ]; then
		echo "$arv - on algarv"
	else
		echo "$arv - ei ole algarv"
	fi
fi
done
