#!/bin/bash
# tervitamise skript

echo -n "Sisesta oma ees- ja perenimi:" #ütleb et sisestaksid oma eesnimi ja perenime
read eesnimi perenimi # tuleb kirjutada enda eesnimi ja perenimi
echo "Tere tulemast, $eesnimi $perenimi" # tervitab sind nende andmetega mis ennem sisestasid
