#!/bin/bash
# Sisesta tärnide arv

echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv: "
read tarn
for (( a=1; a<=$rida; a++ )) #Teeb nii palju ridu nagu sisestasime
do
	for (( b=1; b<=$tarn; b++ )) #Teeb nii palju tärne nagu kirjutasime
	do
	echo -n "* "
	done
echo " "
done
