#!/bin/bash
# Püramiid

echo -n "Sisesta ridade arv: "
read rida
for (( a=1; a<=$rida; a++ )) #Teeb nii palju ridu nagu sisestasime
do
	for (( b=1; b<=$rida; b++ )) #Arvutab märke reas
	do
	if [ $a -ge $b ];then
		echo -n "* " #Kui a on võrdne b-ga siis väljastab * nii mitu korda
else
echo -n " "
fi
	done
echo ""
done
